version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: sdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    command: ["postgres", "-c", "wal_level=logical"]
    volumes:
      - ./sdb/data:/var/lib/postgresql/data
    networks:
      - n1
    healthcheck:
      test: ["CMD", "psql", "-U", "postgres", "-c", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "2048m"
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - ./mongodb_data:/data/db
      - ./mongo-configs/rs-initiate.js:/docker-entrypoint-initdb.d/rs-initiate.js
    ports:
      - 27017:27017
    command: ["mongod","--replSet", "rs0", "--bind_ip_all"]
    networks:
      - n1

networks:
  n1:
    external: true
